version: "3"

services:
  web:
    build:
      context: .
      args:
        - UNAME=${UNAME}
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./data:/home/${UNAME}/data
      - ./pycode:/home/${UNAME}/pycode
    user: ${UID}:${GID}
    ports:
      - 9001:9001
